# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Quotes' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Quotes
  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'SSKeychain'
  pod 'ILRemoteSearchBar'
  pod 'PureLayout'
  pod 'MBProgressHUD'

  target 'QuotesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
