# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Quotes' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Quotes
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '3.5.0'
  pod 'SDWebImage'
  pod 'SSKeychain'
  pod 'ILRemoteSearchBar'
  pod 'PureLayout'
  pod 'MBProgressHUD'
  pod 'MLPAutoCompleteTextField'
  pod 'SwiftAddressBook'
  
  # MOTHER OF GOD!
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |configuration|
              configuration.build_settings['SWIFT_VERSION'] = "2.3"
          end
      end
  end
  
  target 'QuotesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
